import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { findDuplicates, parseIconFileName, toComponentName } from './naming.ts'
import type { DuplicateIcon, ParsedIconFile } from './naming.ts'
import { processSvg, SvgValidationError } from './svg.ts'
import type { ProcessedSvg } from './svg.ts'

export interface GenerateOptions {
  /** Directory searched recursively for `.svg` files. */
  sourceDir: string
  /** Directory that receives the generated modules. Stale files in it are removed. */
  outDir: string
  /** Every icon must provide exactly these drawings. */
  sourceSizes: readonly number[]
  /** Icon names whose colors must be kept even when the icon has a single color. */
  preserveColors?: readonly string[]
  /** Extra public names, each one pointing to the name of an existing icon. */
  aliases?: Readonly<Record<string, string>>
}

export interface GeneratedIcon {
  name: string
  componentName: string
  category: string
  colorMode: ProcessedSvg['colorMode']
  variants: Record<number, ProcessedSvg>
}

export interface InvalidSvg {
  file: string
  problems: string[]
}

export interface InvalidAlias {
  alias: string
  target: string
  problem: string
}

export interface GenerationReport {
  icons: GeneratedIcon[]
  /** Valid aliases, sorted by name. */
  aliases: [alias: string, target: string][]
  invalid: InvalidSvg[]
  invalidAliases: InvalidAlias[]
  duplicates: DuplicateIcon[]
  /** Generated files whose content changed, relative to `outDir`. */
  written: string[]
  /** Stale generated files that were deleted, relative to `outDir`. */
  removed: string[]
}

/** Thrown when any SVG or alias is invalid or duplicated. Nothing is written in that case. */
export class GenerationError extends Error {
  readonly report: GenerationReport

  constructor(report: GenerationReport) {
    super(formatProblems(report))
    this.name = 'GenerationError'
    this.report = report
  }
}

export function formatProblems(report: GenerationReport): string {
  const lines: string[] = []
  if (report.duplicates.length > 0) {
    lines.push(`Duplicated icon names (${report.duplicates.length}):`)
    for (const duplicate of report.duplicates) {
      lines.push(`  "${duplicate.name}" at size ${duplicate.size}:`)
      for (const file of duplicate.files) lines.push(`    - ${file}`)
    }
  }
  if (report.invalid.length > 0) {
    lines.push(`Invalid SVGs (${report.invalid.length}):`)
    for (const invalid of report.invalid) {
      lines.push(`  ${invalid.file}`)
      for (const problem of invalid.problems) lines.push(`    - ${problem}`)
    }
  }
  if (report.invalidAliases.length > 0) {
    lines.push(`Invalid aliases (${report.invalidAliases.length}):`)
    for (const { alias, target, problem } of report.invalidAliases) {
      lines.push(`  "${alias}" -> "${target}": ${problem}`)
    }
  }
  return lines.join('\n')
}

const NAME_PATTERN = /^[a-z0-9]+(-[a-z0-9]+)*$/
const HEADER = '// Generated by scripts/generate-icons.ts. Do not edit.\n'

// Plain code-point order: the same on every machine and locale.
function compare(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0
}

function listFiles(dir: string, extension: string): string[] {
  let entries
  try {
    entries = readdirSync(dir, { withFileTypes: true, recursive: true })
  } catch {
    return []
  }
  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(extension))
    .map((entry) => relative(dir, join(entry.parentPath, entry.name)).replaceAll('\\', '/'))
    .sort(compare)
}

function quote(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\r?\n/g, '\\n')}'`
}

function renderIconModule(icon: GeneratedIcon): string {
  const entries = Object.entries(icon.variants).map(([size, variant]) => {
    const standardViewBox = `0 0 ${size} ${size}`
    const value =
      variant.viewBox === standardViewBox
        ? quote(variant.body)
        : `[${quote(variant.viewBox)}, ${quote(variant.body)}]`
    return `  ${size}: ${value},\n`
  })
  return (
    HEADER +
    `import type { AzIconData } from '../../types.js'\n\n` +
    `/** \`${icon.name}\` (${icon.category}) */\n` +
    `const ${icon.componentName}: AzIconData = {\n${entries.join('')}}\n\n` +
    `export default ${icon.componentName}\n`
  )
}

type Alias = [alias: string, target: string]

/** Every public name with the icon module it loads, sorted by name. */
function publicNames(icons: GeneratedIcon[], aliases: Alias[]): Alias[] {
  return [...icons.map((icon): Alias => [icon.name, icon.name]), ...aliases].sort((a, b) =>
    compare(a[0], b[0]),
  )
}

function renderNames(icons: GeneratedIcon[], aliases: Alias[]): string {
  const union = publicNames(icons, aliases)
    .map(([name]) => `  | ${quote(name)}\n`)
    .join('')
  return (
    HEADER +
    `\n/** Name of every icon available in the library. */\nexport type AzIconName =\n${union}`
  )
}

function renderLoaders(icons: GeneratedIcon[], aliases: Alias[]): string {
  const entries = publicNames(icons, aliases)
    .map(([name, target]) => `  ${quote(name)}: () => import('./icons/${target}.js'),\n`)
    .join('')
  return (
    HEADER +
    `import type { AzIconLoader } from '../types.js'\n` +
    `import type { AzIconName } from './icon-names.js'\n\n` +
    `/** One dynamic import per icon: each entry is a split point for the bundler. */\n` +
    `export const iconLoaders: Readonly<Record<AzIconName, AzIconLoader>> = {\n${entries}}\n`
  )
}

function renderList(icons: GeneratedIcon[], aliases: Alias[]): string {
  const aliasEntries = aliases
    .map(([alias, target]) => `  ${quote(alias)}: ${quote(target)},\n`)
    .join('')
  const names = icons.map((icon) => `  ${quote(icon.name)},\n`).join('')
  const categories = new Map<string, string[]>()
  for (const icon of icons) {
    const list = categories.get(icon.category)
    if (list) list.push(icon.name)
    else categories.set(icon.category, [icon.name])
  }
  const groups = [...categories.keys()]
    .sort(compare)
    .map((category) => {
      const items = categories
        .get(category)!
        .map((name) => quote(name))
        .join(', ')
      return `  ${quote(category)}: [${items}],\n`
    })
    .join('')
  return (
    HEADER +
    `import type { AzIconName } from './icon-names.js'\n\n` +
    `export const azIconNames: readonly AzIconName[] = [\n${names}]\n\n` +
    `export const azIconCategories: Readonly<Record<string, readonly AzIconName[]>> = {\n${groups}}\n\n` +
    `export const azIconAliases: Readonly<Record<string, AzIconName>> = {\n${aliasEntries}}\n`
  )
}

/**
 * Reads every SVG under `sourceDir` and writes the icon modules, the loader registry
 * and the `AzIconName` type to `outDir`.
 *
 * The output depends only on the content of the SVGs: running it twice, on any machine,
 * produces the same files.
 */
export function generateIcons(options: GenerateOptions): GenerationReport {
  const { sourceDir, outDir, sourceSizes } = options
  const preserveColors = new Set(options.preserveColors ?? [])
  const report: GenerationReport = {
    icons: [],
    aliases: [],
    invalid: [],
    invalidAliases: [],
    duplicates: [],
    written: [],
    removed: [],
  }

  const parsed: ParsedIconFile[] = []
  for (const file of listFiles(sourceDir, '.svg')) {
    try {
      const icon = parseIconFileName(file)
      if (!sourceSizes.includes(icon.size)) {
        throw new Error(`size ${icon.size} is not one of ${sourceSizes.join(', ')}`)
      }
      parsed.push(icon)
    } catch (error) {
      report.invalid.push({ file, problems: [(error as Error).message] })
    }
  }
  report.duplicates = findDuplicates(parsed)

  const byName = new Map<string, ParsedIconFile[]>()
  for (const icon of parsed) {
    const list = byName.get(icon.name)
    if (list) list.push(icon)
    else byName.set(icon.name, [icon])
  }

  for (const name of [...byName.keys()].sort(compare)) {
    const files = byName.get(name)!
    const missing = sourceSizes.filter((size) => !files.some((file) => file.size === size))
    if (missing.length > 0) {
      report.invalid.push({
        file: files[0]!.file,
        problems: [`icon "${name}" is missing the drawings for size ${missing.join(', ')}`],
      })
    }

    const variants: Record<number, ProcessedSvg> = {}
    for (const file of files) {
      try {
        variants[file.size] = processSvg(readFileSync(join(sourceDir, file.file), 'utf8'), {
          idPrefix: `az-${name}-${file.size}`,
          preserveColors: preserveColors.has(name),
        })
      } catch (error) {
        if (!(error instanceof SvgValidationError)) throw error
        report.invalid.push({ file: file.file, problems: error.problems })
      }
    }

    const processed = Object.values(variants)
    report.icons.push({
      name,
      componentName: toComponentName(name),
      category: files[0]!.category,
      colorMode: processed.some((variant) => variant.colorMode === 'multi') ? 'multi' : 'mono',
      variants,
    })
  }

  const aliases = Object.entries(options.aliases ?? {}).sort((a, b) => compare(a[0], b[0]))
  for (const [alias, target] of aliases) {
    let problem: string | undefined
    if (!NAME_PATTERN.test(alias)) problem = 'the alias must be kebab-case'
    else if (byName.has(alias)) problem = 'an icon with this name already exists'
    else if (!byName.has(target)) problem = 'the target icon does not exist'
    if (problem) report.invalidAliases.push({ alias, target, problem })
    else report.aliases.push([alias, target])
  }

  report.invalid.sort((a, b) => compare(a.file, b.file))
  if (
    report.invalid.length > 0 ||
    report.invalidAliases.length > 0 ||
    report.duplicates.length > 0
  ) {
    throw new GenerationError(report)
  }

  const files = new Map<string, string>([
    ['icon-names.ts', renderNames(report.icons, report.aliases)],
    ['icon-loaders.ts', renderLoaders(report.icons, report.aliases)],
    ['icon-list.ts', renderList(report.icons, report.aliases)],
  ])
  for (const icon of report.icons) files.set(`icons/${icon.name}.ts`, renderIconModule(icon))

  for (const stale of listFiles(outDir, '.ts')) {
    if (files.has(stale)) continue
    rmSync(join(outDir, stale))
    report.removed.push(stale)
  }
  for (const [file, content] of files) {
    const target = join(outDir, file)
    let current: string | undefined
    try {
      current = readFileSync(target, 'utf8')
    } catch {
      current = undefined
    }
    if (current === content) continue
    mkdirSync(dirname(target), { recursive: true })
    writeFileSync(target, content)
    report.written.push(file)
  }
  return report
}
